### ISSUE TITLE
Update documentation for 1.1 release

### ISSUE THREAD

**Issue by sumo-drosiek** [SumoLogic/sumologic-kubernetes-collection#680]
- [x] ~Add information about using `--force` flag regarding #676 [details](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/676#discussion_r430537042)~ see comment below

**Comment by sumo-drosiek** [comment]
- [ ] Update documentation for custom sources #672 [details](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/672#issuecomment-634596028)

**Comment by sumo-drosiek** [comment]
- [ ] Add examples for customizable kubernetes terraform object #675 [details](https://github.com/SumoLogic/sumologic-kubernetes-collection/pull/675)

**Comment by sumo-drosiek** [comment]
I tested again the helm upgrade for #676 and it updated without `--force` flag
